spring.application.name=PaymentService

server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/PaymentService
spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${db_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.properties.spring.json.trusted.packages=*

spring.kafka.producer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonSerializer

payment.stripe.secret-key=${STRIPE_SECRET_KEY}
payment.stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}


payment.razorpay.key-id=rzp_test_xxxxxxxxx
payment.razorpay.key-secret=xxxxxxxxx
payment.razorpay.webhook-secret=xxxxxxxxx

